### ISSUE TITLE
Workflow: creation of examples and uploading to tudatpy-examples

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudatpy-examples#13]
Right now, new examples have to be manually copied from the tudat-space repo to tudatpy-examples (or vice-versa), as well as manually converted from jupyter notebooks to py files (or the other way around).

Ideally, the examples should only be modified as jupyter files in tudat-space and automatically copied as jupyter and py files to tudatpy-examples. 

If that automatic workflow is not possible (or at least while it isn't implemented), people working on examples should only modify them in the tudat-space repo. Only afterwards should they be copied to the tudatpy-examples repo. The goal is to have all the more recent versions of the examples in a single repo and in a single file type (to avoid having the two repos with a mix of new and old files), as the likelihood of someone forgetting to copy the examples to the repo they are not using relatively large.

**Comment by DominicDirkx** [comment]
Done!
