### ISSUE TITLE
Galileo Constellation Simulator

### ISSUE THREAD

**Issue by Stephan801** [tudat-team/tudatpy-examples#14]
Hi at all,

I just wanted to suggest if the galileo constellation simulator could be converted as well, as it is a brilliant example to make pupils curious about the STEAM field. Thank you.

Best,
Stephan

**Comment by DominicDirkx** [comment]
Hi Stephan,

I had a little spare time, and felt that this was a very noble endeavour!  Attached is the Galileo example (just modify the file extension back to .py). It doesn't have any visualization, so you'll have to add that yourself (and convert it to a notebook if you want). If you make any extensions you think would be useful for others, it would be great if you could share it.

Also, if you'd like to be added to our Slack channel, where you could ask questions, follow our development, and contribute to the project if you'd like, send me an e-mail (see https://docs.tudat.space/en/stable/_src_about/contribute.html). 

Best,

Dominic
[galileo_propagation.txt](https://github.com/tudat-team/tudatpy-examples/files/10202304/galileo_propagation.txt)

**Comment by Stephan801** [comment]
Hi @DominicDirkx ,

thank you very much. I will elaborate on the example and will be happy to share it with you!

Best 

Stephan
