### ISSUE TITLE
Clarification for PyGMO examples 

### ISSUE THREAD

**Issue by irmakcavdar** [tudat-team/tudatpy-examples#16]
In general, the PyGMO examples are very well detailed especially the asteroid orbit optimization. However, the examples lacks the information that provides why the input arguments of the UDP class is defined as a lambda function arguments. Perhaps this is something required for PyGMO to be compatible but it could be nice if it is clarified why this is done and whether or not if it is mandatory, meaning if the code can still work if these attributes are not set as functions but set as variables instead. (I am assuming it won't work).

**Comment by DominicDirkx** [comment]
Good point, this is related to the use of the pickle library to serialize pygmo. This was already on Sean's todo list, so I'm assigning him :)

**Comment by irmakcavdar** [comment]
That is great thank you! And now that we are on the topic, if these attributes are not functions I assume the pygmo will not work, is that correct? (Currently I have multiple errors in my code so I didn't come to point of fixing this part yet :D)

**Comment by DominicDirkx** [comment]
>  if these attributes are not functions I assume the pygmo will not work, is that correct?

**Comment by sbcowan** [comment]
This is also done for tudat-space in [this commit](https://github.com/tudat-team/tudat-space/commit/8202c51fe96516836f0b4407fbe7b2e6e69610c1).
