### ISSUE TITLE
Automated conversion between .py and .ipynb

### ISSUE THREAD

**Issue by sbcowan** [tudat-team/tudatpy-examples#22]
While there are ways to convert the .ipynb to .py and vice versa, both directions bring certain unwanted issues that should be addressed.

**From .ipynb to .py**
The go-to way is to use `jupyter nbconvert --to script 'example.ipynb'`. This results in a working example. This can be followed up with using the [clean_py_notebooks.py](https://github.com/tudat-team/tudatpy-examples/blob/master/clean_py_notebooks.py) to make them more usable, however there are still empty quotes left over. Furthermore, it converts all the files in hard coded directories.

Solution: 
1. Improve [clean_py_notebook.py](https://github.com/tudat-team/tudatpy-examples/blob/master/clean_py_notebooks.py) to get rid of empty """ strings.
2. Create a script that combines the command above with the [clean_py_notebooks.py](https://github.com/tudat-team/tudatpy-examples/blob/master/clean_py_notebooks.py) file so that the conversion from .ipynb to .py is seamless. The script should allow you to both choose specific files to be converted, and in addition also convert whole example libraries.

**From .py to .ipynb**
This direction is of lesser importance because the .ipynb will remain the actively developed examples. There are two options:
- The [convert_py_to_ipynb.py](https://github.com/tudat-team/tudatpy-examples/blob/master/convert_py_to_ipynb.py) file just creates one big code cell in a .ipynb file.
- The p2j (installed with pip) package does allocate code and markdown cells properly, but introduces countless `<br>` instances and does not allocate headers in markdown cells consistently.

The two options are both sub-optimal, which could use more work in the future also by means of a script.

**Comment by larshinueber** [comment]
Following up on this, the `create_script.py` script allows to convert `.ipynb` notebooks to `.py` files using `jupyter nbconvert` and cleans them afterwards.
However, this conversion is not perfect and some issues need to be fixed:

- [ ] Some code cells will get commented out in block quotes. It seems this occurs whenever a Markdown cell has a title and no body. See for example `estimation_with_mpc.ipynb`, code cell 1, where the first part of the import statements are turned into a comment block in the `.py` file or `aoo_design_space_exploration.ipynb`, same with the import statement and the ephemeris settings in code cell 3.
- [ ] If the notebook ends with a Markdown cell, the block comment is not closed at the end of the `.py` file. See `two_stage_rocket_ascent.py`
- [ ] If a function body is split up in multiple code cells, the indentation of the generated `.py` file does not respect this. See e.g. `hodographic_shaping_mga_optimization.ipynb`, cell 4ff.
