### ISSUE TITLE
Several example applications do not work

### ISSUE THREAD

**Issue by stasklav** [tudat-team/tudatpy-examples#23]
The example applications "Keplerian satellite orbit" and "Solar System Propagation" (and possibly more) return errors.

The errors I met in the "Keplerian satellite orbit" are the following:

- In the script block [8] of the .ipynb file (or line 174 of the .py file):
![image](https://user-images.githubusercontent.com/57685183/229512692-77104fce-03bc-4213-a1d5-1874ad3dd14d.png)

I bypassed this by modifying the input of the _runge_kutta_4_ function as follows:
integrator_settings = propagation_setup.integrator.runge_kutta_4(fixed_step_size, fixed_step_size)

- In the script block [8] of the .ipynb file (or lines 177-185 of the .py file):
![image](https://user-images.githubusercontent.com/57685183/229514216-a54619c3-60b3-466f-8d29-2c51484a8c7e.png)

I bypassed this by modifying the input of the _translational_ function by omitting the _simulation_start_epoch_ and _integrator_settings_ input as follows:
propagator_settings = propagation_setup.propagator.translational(
    central_bodies,
    acceleration_models,
    bodies_to_propagate,
    initial_state,
    termination_settings
)

- In the script block [9] of the .ipynb file (or line 205 of the .py file):
![image](https://user-images.githubusercontent.com/57685183/229514817-bab80263-1a3c-4fa5-8e31-4fc31c4d9087.png)

At this point I attempted to run the "Solar System Propagation" example application but it returned similar errors.

The "Keplerian satellite orbit" example application seems to work fine before the last commit (The commit with SHA fff7b202fb395ede3acbd6f24791a540a80c490c is functional).

**Comment by DominicDirkx** [comment]
From the look of your output, it seems that your tudatpy version is out of date. You should have version 0.7.2 of tudatpy.
