### ISSUE TITLE
Make existing examples standard

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudatpy-examples#4]
Picking up from #1.

Existing examples to be updated following a more "standard" template:

- [x] `keplerian_satellite_orbit.py`
- [x] `perturbed_satellite_orbit.py`
- [x] `linear_sensitivity_analysis.py `
- [x] `solar_system_propagation.py`
- [x] `satellite_separation_via_differential_drag.py`
- [x]  an estimation script , which is ready to be formatted in the same style as the example scripts listed above and even incorporated as a guided estimation example on tudat-space
- [x]  a thrust (orbit raising) script, which is ready to be formatted in the same style as the example scripts listed above   (`thrust_between_Earth_Moon.py`, previously named `earth_moon_transfer.py`,)
- [x] `reentry_trajectory.py`: a reentry script, which has an issue with the guidance scheme and is therefore not ready for publishing (but could still be styled)

Checks required for each example are:
- it should run on the latest tudatpy
- it should have an "intro" ("abstract")
- it should be properly commented and follow PEP 8 (more or less)
- (optional) it should be written in a Jupyter notebook, then turned into a `.py` script (automatically)

**Comment by FilippoOggionni** [comment]
@DominicDirkx I was unable to figure out exactly the purpose and settings of the following examples:

- `earth_moon_transfer.py` (and `earth_moon_transfer_custom_environment_settings.py`)
- `reentry_trajectory.py`

Could you please let us know something about them?

**Comment by jo11he** [comment]
If I remember correctly `earth_moon_transfer.py` was abandoned and rewritten to the orbit raising with low-thrust example, so you can take that off the bulleted list. The reentry example is a demonstration of how the vehicle aerodynamic interface can be used to implement an aerodynamic guidance scheme. The reentry topic also appears twice on the list above. 

The estimation example was set up by Dominic and even incorporated as a guided example to tudat-space. I did not notice that before today.

**Comment by gaffarelj** [comment]
The current plan on my end is then to do the following:
- Document, clean, and proofread the `earth_moon_transfer.py` example, and rename it to something more appropriate.
- Fix, document, and clean the `reentry_trajectory.py` example.

Finally, the `earth_moon_transfer_custom_environment_settings.py` does not seem to bring anything significantly new to the table, and could be deleted. Can you confirm @DominicDirkx ?

**Comment by FilippoOggionni** [comment]
Thanks @gaffarelj !

Update:
- I deleted `earth_moon_transfer_custom_environment_settings.py`
- I added an `input` subdirectory for the space shuttle aerodynamic coefficient files
- I moved `earth_moon_transfer.py` and `reentry_trajectory.py` (now on @gaffarelj's plate) to a `to_be_revised` subdirectory, so that users visiting the repo avoid looking at those two examples

**Comment by gaffarelj** [comment]
I have commented, the `earth_moon_transfer.py` example, and added a couple of dependent variables and plots to it. Also, I renamed it to `thrust_between_Earth_Moon.py`.

I have tuned the `reentry_trajectory.py` example to limit skipping to a minimum (while keeping the g-load relatively low). I also changed the dependent variables and plots from this example.

Both of these examples have been moved out of the `to_be_revised` folder, as I see them as good to be used now.

Looking at the original task list of this issue, I think that they are all satisfactory now. The thrust (orbit raising) script is in fact the `thrust_between_Earth_Moon.py` example.

@FilippoOggionni I let you close this issue if you agree (and open a new one concerning the creation of the notebooks?).

**Comment by FilippoOggionni** [comment]
Thanks @gaffarelj  👍 I will move the issue to the revision column.

Before closing the issue, I wanted to make sure that the estimation example is finished. To this regard, @DominicDirkx, we noticed `feature/estimation_example` branch is 13 commits behind `main`, but the estimation example is already documented on tudat-space. Could you please close the issue once the estimation example is done?

**Comment by DominicDirkx** [comment]
I've resolved the review in the pull request, and have pushed a few very minor modifications to the documentation. I'm closing this issue, great to see how this page has shaped up!

**Comment by DominicDirkx** [comment]
I've made some minor changes to the estimation example, and have push the branch and merged it into master (#5)

**Comment by FilippoOggionni** [comment]
Awesome, thanks! Then I will close this.

Regarding the inconsistencies, I agree, we can take care of them when we convert to Jupyter notebooks (reminder for @gaffarelj).
