### ISSUE TITLE
Correct typo in keplerian_satellite.py propagation example

### ISSUE THREAD

**Issue by luigigisolfi** [tudat-team/tudatpy-examples#46]
In the keplerian_satellite.py propagation example: change the lines "And the velocity vector of Delfi-C3 is [km/s]: \n{     states[simulation_start_epoch.to_float()][3:] / 1E3}" to "And the velocity vector of Delfi-C3 is [km/s]: \n{     states[simulation_end_epoch.to_float()][3:] / 1E3}

**Comment by DominicDirkx** [comment]
@luigigisolfi Is this fixed?

**Comment by luigigisolfi** [comment]
Fixed!
