### ISSUE TITLE
Add rocket ascent example

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudatpy-examples#6]
A new example should be made about the ascent of a solid rocket on Mars.

This can showcase a basic model for thrust (off when no more propellant), of translational + mass propagation, and of the use of selected dependent variables, including a custom one.

**Comment by gaffarelj** [comment]
@FilippoOggionni and @DominicDirkx please feel free to comment on this new example when you have the time 🙂

**Comment by DominicDirkx** [comment]
Oh, this is nice! With two small additions, I think this can go into the repo:

* In several places (thrust magnitude, thrust direction, angle of attack), you have implemented a custom equation. Could you add the equations explicitly into the notebook (as a latex-like equation in the text) to make explicit what you've done
* Write a brief section (a couple short paragraphs) explaining the results, and presenting why they come out the way they do, based on the settings that are provided

I think for all students working on ascent, this is going to be a really useful example. Many thanks

**Comment by FilippoOggionni** [comment]
I will have a deeper look into this in the next few days! Looks really nice though 🙂

**Comment by gaffarelj** [comment]
Thanks,
I have just pushed 22eb33a183441cce8a63ad74b80dad6d4abdc234 to add the equations of the model/guidance that I setup, and a section at the end to describe the results.
