### ISSUE TITLE
Error in propagation examples (reentry_trajectory.py)

### ISSUE THREAD

**Issue by luigigisolfi** [tudat-team/tudatpy-examples#61]
# Setup the aerodynamic coefficients settings tabulated from the files
coefficient_settings = environment_setup.aerodynamic_coefficients.tabulated_force_only_from_files(
    force_coefficient_files=aero_coefficients_files,
   reference_area=2690.0*0.3048*0.3048,
   independent_variable_names=[environment.angle_of_attack_dependent, environment.mach_number_dependent],
    are_coefficients_in_aerodynamic_frame=True,
    are_coefficients_in_negative_axis_direction=True
)

Triggers the error:
TypeError: tabulated_force_only_from_files(): incompatible function arguments. The following argument types are supported:
    1. (force_coefficient_files: dict[int, str], reference_area: float, independent_variable_names: list[tudatpy.kernel.numerical_simulation.environment.AerodynamicCoefficientsIndependentVariables], force_coefficients_frame: tudatpy.kernel.numerical_simulation.environment.AerodynamicCoefficientFrames = <AerodynamicCoefficientFrames.negative_aerodynamic_frame_coefficients: 2>, interpolator_settings: tudatpy.kernel.math.interpolators.InterpolatorSettings = None) -> tudatpy.kernel.numerical_simulation.environment_setup.aerodynamic_coefficients.AerodynamicCoefficientSettings

Invoked with: kwargs: force_coefficient_files={0: 'input/STS_CD.dat', 2: 'input/STS_CL.dat'}, reference_area=249.90917760000002, independent_variable_names=[<AerodynamicCoefficientsIndependentVariables.angle_of_attack_dependent: 1>, <AerodynamicCoefficientsIndependentVariables.mach_number_dependent: 0>], are_coefficients_in_aerodynamic_frame=True, are_coefficients_in_negative_axis_direction=True

For now solved with:
# Setup the aerodynamic coefficients settings tabulated from the files
coefficient_settings = environment_setup.aerodynamic_coefficients.tabulated_force_only_from_files(
    force_coefficient_files=aero_coefficients_files,
    reference_area=2690.0*0.3048*0.3048,
    independent_variable_names=[environment.angle_of_attack_dependent, environment.mach_number_dependent],
)

**Comment by DominicDirkx** [comment]
I'll have a look at this

**Comment by DominicDirkx** [comment]
It's been fixed, there were two problems:
* The code was using a deprecated interface which was removed recently, leading to the error
* (separate from this issue) there was an issue with the automatic conversionof notebook to Python.
@luigigisolfi Could you make the modification to the notebook so that the conversion is robust?

you can see the change I had to make here:
https://github.com/tudat-team/tudatpy-examples/commit/c36babcfe1ee425bfbb461ecdd1a8faffc4abbf4

**Comment by luigigisolfi** [comment]
Applied the changes and made sure the py script works. Thanks
