### ISSUE TITLE
Examples not fully working: 1) improved_estimation_with_mpc

### ISSUE THREAD

**Issue by luigigisolfi** [tudat-team/tudatpy-examples#66]
Error in the function "perfrom_estimation" defined within the code. Checking the source code, it looks like the **set_weights_from_observation_collection** is a CovariancaAnalysisInput attribute, not an EstimationInput attribute. 

`Traceback (most recent call last):
  File "/Users/lgisolfi/Desktop/tudatpy-examples/estimation/improved_estimation_with_mpc.py", line 1012, in <module>
    pod_output, batch, observation_collection, estimator = perform_estimation(
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/lgisolfi/Desktop/tudatpy-examples/estimation/improved_estimation_with_mpc.py", line 582, in perform_estimation
    pod_input.set_weights_from_observation_collection()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tudatpy.kernel.numerical_simulation.estimation.Est' object has no attribute 'set_weights_from_observation_collection'`

**Comment by DominicDirkx** [comment]
This may be due to the version of tudat, which one are you using?

**Comment by luigigisolfi** [comment]
I am not sure how to check that. However, if I run:

` conda install --update-deps -c tudat-team tudat`

I get

```
Channels:
 - tudat-team
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides boost-cpp >=1.72.0,<1.72.1.0a0 needed by tudat-2.12.0-h68db2cf_0

Could not solve for environment specs
The following packages are incompatible
└─ tudat is not installable because there are no viable options
   ├─ tudat [2.12.0|2.12.1] would require
   │  └─ boost-cpp >=1.72.0,<1.72.1.0a0 , which does not exist (perhaps a missing channel);
   ├─ tudat [2.12.1|2.13.0] would require
   │  └─ boost-cpp >=1.78.0,<1.78.1.0a0 , which does not exist (perhaps a missing channel);
   └─ tudat 2.13.0 would require
      └─ boost-cpp >=1.84.0,<1.85.0a0 , which does not exist (perhaps a missing channel).


```

and similar for tudatpy

```
Channels:
 - tudat-team
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides python >=3.10,<3.11.0a0 *_cpython needed by tudatpy-0.7.1-py310he2e606d_1

Could not solve for environment specs
The following packages are incompatible
└─ tudatpy is not installable because there are no viable options
   ├─ tudatpy [0.7.1|0.7.2|0.7.3.dev25] would require
   │  └─ python >=3.10,<3.11.0a0 *_cpython, which does not exist (perhaps a missing channel);
   ├─ tudatpy [0.7.1|0.7.2|0.7.3.dev25] would require
   │  └─ python >=3.8,<3.9.0a0 *_cpython, which does not exist (perhaps a missing channel);
   ├─ tudatpy [0.7.1|0.7.2|0.7.3.dev25] would require
   │  └─ python >=3.9,<3.10.0a0 *_cpython, which does not exist (perhaps a missing channel);
   ├─ tudatpy [0.7.2|0.7.3] would require
   │  └─ libcxx >=15.0.7 , which does not exist (perhaps a missing channel);
   └─ tudatpy 0.8.0 would require
      └─ astroquery, which does not exist (perhaps a missing channel).
```

So i suppose i am on tudat 2.12.0 and tudatpy 0.7.1 (?)

**Comment by DominicDirkx** [comment]
You can use `conda list ` to get a list of packages in your active environment. Are you using your own built kernel or a conda package? In either case, you should use the develop package
